# Generated by Django 4.2.7 on 2024-12-06 06:42

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('leads', 'Category')
    UserProfile = apps.get_model('leads', 'UserProfile')
    
    # Get all existing user profiles
    user_profiles = UserProfile.objects.all()
    
    # Default categories
    default_categories = ['New', 'Contacted', 'In Progress', 'Lost', 'Converted']
    
    # Create categories for each organization
    for profile in user_profiles:
        for category_name in default_categories:
            Category.objects.get_or_create(
                name=category_name,
                organisation=profile
            )

def reverse_default_categories(apps, schema_editor):
    Category = apps.get_model('leads', 'Category')
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_converted_date'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_default_categories)
    ]
